This is an example of an inefficient parser of the tracker data.  It assumes you have uploaded the file to the compute instance to `/content/sample_data/`. We use plotly to verify the x vs. t and y vs. t graphs and to plot the x-y trajectory.

In [1]:
import plotly.graph_objects as go
import numpy as np

In [2]:
# defining the parser function
def load_tracker_file(filepath):
  data = []
  with open(filepath) as f:
    lines = f.readlines()
    for l in lines[2:]:
      l=l.strip()
      cols = l.split('\t')
      data.append( [float(cols[i]) for i in range(3)])
  arr = np.array( data )

  return arr

In [3]:
# using it to parse the file
mydata = load_tracker_file( "/Users/emmanuelflores/GitHub/Tufts/Spring_2025/Computational_Physics/tracker.txt")

In [4]:
# checking the shape and contents
print(mydata.shape)
print(mydata)

(60, 3)
[[ 7.640e-01 -9.918e+01 -8.385e+01]
 [ 7.730e-01 -9.654e+01 -8.347e+01]
 [ 7.810e-01 -9.322e+01 -8.345e+01]
 [ 7.890e-01 -8.920e+01 -8.290e+01]
 [ 7.980e-01 -8.446e+01 -8.294e+01]
 [ 8.060e-01 -7.947e+01 -8.210e+01]
 [ 8.140e-01 -7.411e+01 -8.240e+01]
 [ 8.220e-01 -6.840e+01 -8.221e+01]
 [ 8.310e-01 -6.218e+01 -8.121e+01]
 [ 8.390e-01 -5.564e+01 -8.044e+01]
 [ 8.470e-01 -4.799e+01 -8.144e+01]
 [ 8.560e-01 -3.949e+01 -7.929e+01]
 [ 8.640e-01 -3.019e+01 -7.834e+01]
 [ 8.720e-01 -2.040e+01 -7.734e+01]
 [ 8.810e-01 -1.012e+01 -7.810e+01]
 [ 8.890e-01  3.040e-01 -7.641e+01]
 [ 8.970e-01  1.097e+01 -7.654e+01]
 [ 9.060e-01  2.229e+01 -7.454e+01]
 [ 9.140e-01  3.417e+01 -7.569e+01]
 [ 9.220e-01  4.646e+01 -7.487e+01]
 [ 9.300e-01  5.972e+01 -7.495e+01]
 [ 9.390e-01  7.296e+01 -7.479e+01]
 [ 9.470e-01  8.687e+01 -7.473e+01]
 [ 9.550e-01  1.016e+02 -7.415e+01]
 [ 9.640e-01  1.167e+02 -7.398e+01]
 [ 9.720e-01  1.321e+02 -7.436e+01]
 [ 9.800e-01  1.482e+02 -7.435e+01]
 [ 9.890e-01  1.642e

In [5]:
# Also here is a proper one line solution
mydata = np.loadtxt('/Users/emmanuelflores/GitHub/Tufts/Spring_2025/Computational_Physics/tracker.txt', delimiter='\t', skiprows=2)
print(mydata.shape)
print(mydata)

(60, 3)
[[ 7.640e-01 -9.918e+01 -8.385e+01]
 [ 7.730e-01 -9.654e+01 -8.347e+01]
 [ 7.810e-01 -9.322e+01 -8.345e+01]
 [ 7.890e-01 -8.920e+01 -8.290e+01]
 [ 7.980e-01 -8.446e+01 -8.294e+01]
 [ 8.060e-01 -7.947e+01 -8.210e+01]
 [ 8.140e-01 -7.411e+01 -8.240e+01]
 [ 8.220e-01 -6.840e+01 -8.221e+01]
 [ 8.310e-01 -6.218e+01 -8.121e+01]
 [ 8.390e-01 -5.564e+01 -8.044e+01]
 [ 8.470e-01 -4.799e+01 -8.144e+01]
 [ 8.560e-01 -3.949e+01 -7.929e+01]
 [ 8.640e-01 -3.019e+01 -7.834e+01]
 [ 8.720e-01 -2.040e+01 -7.734e+01]
 [ 8.810e-01 -1.012e+01 -7.810e+01]
 [ 8.890e-01  3.040e-01 -7.641e+01]
 [ 8.970e-01  1.097e+01 -7.654e+01]
 [ 9.060e-01  2.229e+01 -7.454e+01]
 [ 9.140e-01  3.417e+01 -7.569e+01]
 [ 9.220e-01  4.646e+01 -7.487e+01]
 [ 9.300e-01  5.972e+01 -7.495e+01]
 [ 9.390e-01  7.296e+01 -7.479e+01]
 [ 9.470e-01  8.687e+01 -7.473e+01]
 [ 9.550e-01  1.016e+02 -7.415e+01]
 [ 9.640e-01  1.167e+02 -7.398e+01]
 [ 9.720e-01  1.321e+02 -7.436e+01]
 [ 9.800e-01  1.482e+02 -7.435e+01]
 [ 9.890e-01  1.642e

In [6]:
# Plot x and y vs time
fig = go.Figure()
fig.add_trace( go.Scatter(x=mydata[:,0], y=mydata[:,1], mode='lines',name='x'))
fig.add_trace( go.Scatter(x=mydata[:,0], y=mydata[:,2], mode='lines',name='y'))
fig.update_layout(title='Track Data', xaxis_title='time', yaxis_title='pos')
fig.show()

In [7]:
# Plot X-Y trajectory
fig_traj = go.Figure()
fig_traj.add_trace( go.Scatter(x=mydata[:,1], y=mydata[:,2], mode='lines',name='trajectory'))
fig_traj.update_layout(title='Trajectory', xaxis_title='X', yaxis_title='Y')
fig_traj.show()